# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-23 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='if_staff',
            new_name='is_staff',
        ),
    ]
